"""empty message

Revision ID: 14d7d9e3bc37
Revises: 57109ae08de3
Create Date: 2015-03-05 16:38:58.954614

"""

# revision identifiers, used by Alembic.
revision = '14d7d9e3bc37'
down_revision = '57109ae08de3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cf_apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cf_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['key'], ['cf_apikey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cf_domain_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['cf_domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cf_domain_access')
    op.drop_table('cf_domain')
    op.drop_table('cf_apikey')
    ### end Alembic commands ###
