"""empty message

Revision ID: 40f4030404bd
Revises: 494344081a73
Create Date: 2015-03-05 16:32:22.021630

"""

# revision identifiers, used by Alembic.
revision = '40f4030404bd'
down_revision = '494344081a73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
