"""empty message

Revision ID: 4b78932ba70e
Revises: 40f4030404bd
Create Date: 2015-03-05 16:35:13.717800

"""

# revision identifiers, used by Alembic.
revision = '4b78932ba70e'
down_revision = '40f4030404bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
