"""empty message

Revision ID: 57109ae08de3
Revises: 4b78932ba70e
Create Date: 2015-03-05 16:37:07.068661

"""

# revision identifiers, used by Alembic.
revision = '57109ae08de3'
down_revision = '4b78932ba70e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
